### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by AntonKartavyy** [leoneedpro/instagram-parser#1]
Здравствуйте! Ваш скрипт не работает! Если не затруднит отправьте пожалуйста рабочий скрипт на почту sale.office@list.ru буду очень презнателен

**Comment by leoneedpro** [comment]
Привет, скрипт рабочий) Вопрос только в том, что он прожорлив на оперативную память и зависит кол-ва сбора подписчиков. Кстати, сделал новое решение:

Новый парсер Instagram

- Теперь собирает базу подписчиков со скоростью 2500-3000 в секунду.
- Выгружает в текстовый формат (txt)
- Также сделал парсинг телефонных номеров и выгрузку в Excel таблицы (xlsx).

Интервалы для сбора определенного кол-ва реализую позже, а также кнопку "стоп" для принудительной остановки.

В планах сделать мнопоточность для увеличения скорости сбора, парсинг хештегов и геолокаций с аккаунтов, и определения принадлежности по регионам.
Все это реализовал на базе бота в telegram

Сейчас находится в тестовом режиме, поставил ограничитель на сбор в 25 000 аккаунтов, как допишу сниму)

http://t.me/instaparser_bot

**Comment by IndraLungSpirit** [comment]
Автор, а можешь сделать сбор по геолокациям? готов дать денюжку не большую
